apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m5muo4bip-java-quarkus 
  janus-idp.io/tekton: m5muo4bip-java-quarkus
  backstage.io/kubernetes-id: m5muo4bip-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m5muo4bip-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml